package example

// Code generated by "fiberopenapi -spec ./petstore-simple.json"; DO NOT EDIT.

import (
	"errors"
	"fmt"
)

var (
	ErrMaxLength = errors.New("maxLength")
	ErrMinLength = errors.New("minLength")
)

type ValidationError struct {
	Err error
}

func (e ValidationError) Error() string {
	if e.Err != nil {
		return e.Err.Error()
	}
	return ""
}

func (e ValidationError) Unwrap() error {
	return e.Err
}

func NewValidationError(format string, a ...any) error {
	return ValidationError{Err: fmt.Errorf(format, a...)}
}

func NewMaxLengthError(got int, want int) error {
	return NewValidationError("%w: got %d, want %d", ErrMaxLength, got, want)
}

func NewMinLengthError(got int, want int) error {
	return NewValidationError("%w: got %d, want %d", ErrMinLength, got, want)
}

type Null struct{}

type nullable interface {
	IsNull() bool
}

func IsNull(v any) bool {
	if v == nil {
		return false
	}
	if n, ok := v.(nullable); ok {
		return n.IsNull()
	}
	return false
}

type FindPetId int

type UpdatePetId int
