package router

// Code generated by "fiberopenapi -spec ./specification.json"; DO NOT EDIT.

type Nullable[T any] struct {
	Value  T
	isNull bool
}

func (n *Nullable[T]) IsNull() bool {
	return n.isNull
}

type Optional[T any] struct {
	Value *T
}

func (o *Optional[T]) IsUndefined() bool {
	return o.Value == nil
}

type ErrorMessage string

type Mark string

type Winner string

type status struct {
	Winner[string] `json:"winner"`
	Board[array]   `json:"board"`
}
