package example

// Code generated by "fiberopenapi -spec ./specification.json"; DO NOT EDIT.

import (
	"encoding/json"

	"github.com/gofiber/fiber/v2"
)

// Implement this interface.
type Handlers interface {
	GetBoard(c *fiber.Ctx) error
	GetSquare(c *fiber.Ctx, row Coordinate, column Coordinate) error
	PutSquare(c *fiber.Ctx, body Mark, row Coordinate, column Coordinate) error
}

type rawHandlers interface {
	GetBoard(c *fiber.Ctx) error
	GetSquare(c *fiber.Ctx) error
	PutSquare(c *fiber.Ctx) error
}

func addRawHandlers(app *fiber.App, h rawHandlers) {
	app.Get("/board", h.GetBoard)
	app.Get("/board/:row/:column", h.GetSquare)
	app.Put("/board/:row/:column", h.PutSquare)
}

type validatedHandlers struct {
	validated Handlers
}

func AddHandlers(app *fiber.App, h Handlers) {
	addRawHandlers(app, &validatedHandlers{h})
}

func (h *validatedHandlers) GetBoard(c *fiber.Ctx) error {
	return h.validated.GetBoard(c)
}

func (h *validatedHandlers) GetSquare(c *fiber.Ctx) error {
	var row Coordinate
	if err := json.Unmarshal([]byte(c.Params("row")), &row); err != nil {
		return err
	}
	var column Coordinate
	if err := json.Unmarshal([]byte(c.Params("column")), &column); err != nil {
		return err
	}
	return h.validated.GetSquare(c, row, column)
}

func (h *validatedHandlers) PutSquare(c *fiber.Ctx) error {
	var body Mark
	if err := json.Unmarshal(c.Body(), &body); err != nil {
		return err
	}
	var row Coordinate
	if err := json.Unmarshal([]byte(c.Params("row")), &row); err != nil {
		return err
	}
	var column Coordinate
	if err := json.Unmarshal([]byte(c.Params("column")), &column); err != nil {
		return err
	}
	return h.validated.PutSquare(c, body, row, column)
}
