package example

// Code generated by "fiberopenapi -spec ./specification.json"; DO NOT EDIT.

import (
	"github.com/gofiber/fiber/v2"
)

type Handlers interface {
	GetBoard(c *fiber.Ctx) error
	GetSquare(c *fiber.Ctx) error
	PutSquare(c *fiber.Ctx) error
}

func AddHandlers(app *fiber.App, h Handlers) {
	app.Get("/board", h.GetBoard)
	app.Get("/board/:row/:column", h.GetSquare)
	app.Put("/board/:row/:column", h.PutSquare)
}

type ValidatedHandlers interface {
	GetBoard(c *fiber.Ctx) error
	GetSquare(c *fiber.Ctx) error
	PutSquare(c *fiber.Ctx) error
}

type HandlersWithValidation struct {
	ValidatedHandlers
}

func (h *HandlersWithValidation) GetBoard(c *fiber.Ctx) error {
	return h.ValidatedHandlers.GetBoard(c)
}
func (h *HandlersWithValidation) GetSquare(c *fiber.Ctx) error {
	return h.ValidatedHandlers.GetSquare(c)
}
func (h *HandlersWithValidation) PutSquare(c *fiber.Ctx) error {
	return h.ValidatedHandlers.PutSquare(c)
}
