package example

// Code generated by "fiberopenapi -spec ./petstore-simple.json"; DO NOT EDIT.

import (
	"encoding/json"

	"github.com/gofiber/fiber/v2"
)

// Implement this interface.
type Handlers interface {
	FindPet(c *fiber.Ctx, id FindPetId) error
	UpdatePet(c *fiber.Ctx, id UpdatePetId) error
}

type rawHandlers interface {
	FindPet(c *fiber.Ctx) error
	UpdatePet(c *fiber.Ctx) error
}

func addRawHandlers(app *fiber.App, h rawHandlers) {
	app.Get("/pet/:id", h.FindPet)
	app.Put("/pet/:id", h.UpdatePet)
}

type validatedHandlers struct {
	validated Handlers
}

func AddHandlers(app *fiber.App, h Handlers) {
	addRawHandlers(app, &validatedHandlers{h})
}

func (h *validatedHandlers) FindPet(c *fiber.Ctx) error {
	var id FindPetId
	if err := json.Unmarshal([]byte(c.Params("id")), &id); err != nil {
		return err
	}
	return h.validated.FindPet(c, id)
}

func (h *validatedHandlers) UpdatePet(c *fiber.Ctx) error {
	var id UpdatePetId
	if err := json.Unmarshal([]byte(c.Params("id")), &id); err != nil {
		return err
	}
	return h.validated.UpdatePet(c, id)
}
