package example

// Code generated by "fiberopenapi -spec ./petstore-simple.json"; DO NOT EDIT.

import (
	"github.com/gofiber/fiber/v2"
)

type Handlers interface {
	FindPet(c *fiber.Ctx) error
	UpdatePet(c *fiber.Ctx) error
}

func AddHandlers(app *fiber.App, h Handlers) {
	app.Get("/pet/:id", h.FindPet)
	app.Put("/pet/:id", h.UpdatePet)
}

type ValidatedHandlers interface {
	FindPet(c *fiber.Ctx) error
	UpdatePet(c *fiber.Ctx) error
}

type HandlersWithValidation struct {
	ValidatedHandlers
}

func (h *HandlersWithValidation) FindPet(c *fiber.Ctx) error {
	return h.ValidatedHandlers.FindPet(c)
}
func (h *HandlersWithValidation) UpdatePet(c *fiber.Ctx) error {
	return h.ValidatedHandlers.UpdatePet(c)
}
